package com.param.config.configclient;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
@RefreshScope
@RestController
@RequestMapping("/config")
public class Message {
	
	@Value("${message:message generated by client}")
	private String message;
	
	@GetMapping("/message")
	public String message() {
		return message;
	}

}
